force-app/main/default/objects/Country__c/fields/alpha2code__c.field-meta.xml
<CustomField>
    <fullName>alpha2code__c</fullName>
    <label>alpha2code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/alpha3code__c.field-meta.xml
<CustomField>
    <fullName>alpha3code__c</fullName>
    <label>alpha3code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/Capital_city__c.field-meta.xml
<CustomField>
    <fullName>Capital_city__c</fullName>
    <label>Capital city</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ExternalServicesCalloutBatch.cls
global class ExternalServicesCalloutBatch implements Database.Batchable<sObject> {
    global Database.QueryLocator start(Database.BatchableContext BC) { 
        String query = 'SELECT Id,Name,alpha2code__c,alpha3code__c,Capital_city__c,region__c,regionalBlocs__c FROM Country__c' ;
        return Database.getQueryLocator(query);
    }
    global void execute(Database.BatchableContext BC, List<Country__c> scope) {
         
    }   
    
    global void finish(Database.BatchableContext BC) {
    }

}